final List<String> textos = [
  'data: 06.02.2024           Hora: 20:50:32 \n\nQueria abrir meu coração por meio do código binários na sua tela <3.',
  'Na minha mente de certa forma escrever sempre foi mais fácil que falar, pois sempre me empolgo, e somente assim posso expressar meus sentimentos verdadeiros de forma que me entendam.',
  'Acho engraçado que a primeira coisa que está na minha frente é nossa foto com jujuba, aquela mesmo que ela tá com uma cara de bunda, parece que ela foi posta aqui simplesmente pra eu escrever com seu sorriso me guiando.',
  'Enfim, lembro da "época" em que nossos assuntos eram só jujuba, rock e o famoso caneta azul',
  'como daquela conversa saiu um dos maiores e mais foda relacionamentos já vistos na face da terra?',
  'Incompreensível, porém, aconteceu, e é engraçado, principalmente quando vejo que existe uma música que contextualizou completamente nossa relação',
  'parece besta porém (vícios e virtudes) é a nossa cara e claro que eu "eternizei" ela numa das nossas fotos :D',
  '"Eu nunca tive muito a ver com ela, o livro que ela ama eu não li", Não tem céus que me faça mudar minha opinião sobre nós dois, somos feitos um pro outro!',
  'E mesmo que nao sejamos almas gêmeas ou nada parecido um com o outro, sigo enfrentando tudo e todos sem abaixar a cabeça.',
  'Afinal "só o que é bom dura tempo o bastante pra se tornar inesquecível" e assim eu percebi que a gente já é o suficiente um pro outro',
  'Complicado tentar explicar com palavras, porém tudo que eu estou vivendo ultimamente, só posso falar algo sobre isso.',
  'obrigado',
  'obrigado por ser essa mulher que, independente de todos meus erros vai me abraçar e me fazer abrir o olho, abrir o olho pra me fazer evoluir como pessoa.',
  'obrigado por me contagiar em todo momento da minha vida com apenas sua presença',
  'obrigado por me fazer parte da sua vida',
  'obrigado obrigado obrigado obrigado obrigado',
  'Porém, obrigado não é o suficiente, obrigado só é uma palavra, assim como tudo que voce leu até agora',
  'Queria dar um significado profundo sobre esse texto, mas tudo isso se resume ao mais simples "Eu te amo".',
  'três palavras que mesmo mudando seu idioma tem o mais profundo peso, na mais pequena frase.',
  'I love you  \n Te quiero \n Je t aime \n Ich liebe dich \n Ti amo \n Aishiteru \n Ya tebya liubliu \n\n EU TE AMO com todo meu ser, Eu te amo \n\n De: namorado/melhor amigo de todo sempre: Felipe Gabriel <3 \n Para: Minha princesa/Ana Clara',
];